"""config.py — reads config.yaml and works out every path in the project.

    from config import *

You do not edit this file. You edit **config.yaml**, right next to it. This one turns
the settings in there into the file paths that notebooks 01-05 read and write.

Every path hangs off ROOT, which is wherever this file physically sits — your group's
shared Drive folder. So there is never a path to type into a notebook, and the file
notebook 02 writes is by construction the file notebook 03 opens.
"""

from pathlib import Path

import yaml

# Anchored to THIS file rather than to the working directory, so the same path works
# whether you run a notebook from notebooks/, from the repo root, or from Colab.
ROOT = Path(__file__).resolve().parent
CONFIG_FILE = ROOT / "config.yaml"

# This is the first thing that happens in every notebook, so it is also the first place
# a mistake in config.yaml can show up. Say what is wrong in words rather than let a
# YAML parser explain itself with a line and column number.
if not CONFIG_FILE.exists():
    raise FileNotFoundError(
        "There is no config.yaml next to config.py.\n"
        "  looked in: " + str(ROOT) + "\n"
        "config.yaml is the one file your group edits, and every path in the project is "
        "worked out from it. Copy it back from the template, or check that the SETUP "
        "cell moved you into your group's shared Drive folder and not somewhere else.")

try:
    settings = yaml.safe_load(CONFIG_FILE.read_text(encoding="utf-8"))
except yaml.YAMLError:
    raise ValueError(
        "config.yaml could not be read. Something in it is not valid YAML.\n"
        "Almost always one of three things:\n"
        "  * a missing space after a colon - it must be `track: cars50`, not "
        "`track:cars50`\n"
        "  * a line indented with a Tab instead of spaces\n"
        "  * a quote opened and not closed\n"
        "Open config.yaml, compare it line by line with the comments in it, and try "
        "again.")


def _setting(name: str):
    """One setting out of config.yaml, or a message naming the line to go and add.

    Args:
        name: the key to read.

    Returns:
        Whatever config.yaml has under that key.

    Raises:
        ValueError: when the key is not there.
    """
    if name not in settings:
        # A ValueError, not a KeyError: KeyError prints its message as a quoted repr,
        # which turns these two lines into one unreadable string with a \n in it.
        raise ValueError(
            "config.yaml has no `" + name + ":` line, and every notebook needs it.\n"
            "Open config.yaml and add it back - the template's copy of the file lists "
            "every setting with a comment explaining what it is for.")
    return settings[name]


TRACK = _setting("track")
GROUP = _setting("group")
RUN = _setting("run")
SEED = _setting("seed")
N_PER_CLASS = _setting("n_per_class")

# How big the dev half is. ONE setting, and its type says which of the two ways you
# meant: a whole number is items per label (dev: 3), a decimal is a proportion of each
# label (dev: 0.35). This used to be two keys, dev_per_class and dev_fraction, of which
# you had to set exactly one — two names, a validator and two call arguments for a
# single decision.
DEV = _setting("dev")

# Left empty in the YAML, these read as None. Downstream code expects a list of members
# and expects None to mean "no label order given", so hand it what it expects.
MEMBERS = _setting("members") or []
LABELS_ORDER = _setting("labels_order") or None

# The two model settings that decide whether anyone can reproduce your run. They live
# here rather than in a notebook cell for the same reason `seed` does: the temperature
# that produced the number in your report has to be the temperature your report states,
# and a value typed into a cell is a value the next person to run the cell can change
# without noticing. PLAN.md asks for both.
#
# `settings.get` rather than `_setting`, so a config.yaml written before these two
# existed still runs - it just gets the reproducible defaults.
TEMPERATURE = settings.get("temperature", 0)
MODEL = settings.get("model") or ""

# Who labels. These are the annotation sheet's coder column headers, and notebooks 03
# and 05 both need them to match — a mismatch used to mean the join in 05 came back
# empty with nothing to say why, because the names were typed separately in each
# notebook. One setting, read by both.
CODERS = _setting("coders") or ["CoderA", "CoderB"]
if len(CODERS) < 2:
    raise ValueError(
        "config.yaml lists " + str(len(CODERS)) + " coder(s) under `coders:`. Double "
        "coding needs at least two: agreement between one person and themselves is not "
        "a number, and notebook 03 has nothing to adjudicate.\n"
        "Then re-run the SETUP cell at the top of this notebook.")


# ----------------------------------------------------------------------------------
# The split check — run before anything else, because it is cheap and it is a design
# error, not a typo.
# ----------------------------------------------------------------------------------
# Two ways to say the same thing, and setting both means you have not decided. Setting
# neither means notebook 03 cannot draw the line between the items you may look at and
# the items you report on, which is the one thing that makes your final number honest.
_SPLIT_HELP = (
    "Set `dev:` in config.yaml to one of these:\n"
    "    dev: 3       a whole number — that many dev items per label\n"
    "    dev: 0.35    a decimal between 0 and 1 — that proportion of each label\n"
    "Then re-run the SETUP cell at the top of this notebook."
)

if DEV is None:
    raise ValueError(
        "config.yaml has `dev:` with nothing after it, so there is no dev/test split.\n"
        "The split is what separates the items you tune your prompt on from the items "
        "you report a score on. Without it, the number in your report is the number you "
        "tuned until it went up.\n"
        + _SPLIT_HELP
    )

# bool before int: in Python `True` IS an int, and `dev: yes` in YAML arrives here as
# True, which would otherwise be read as "1 dev item per label" without complaining.
if isinstance(DEV, bool) or not isinstance(DEV, (int, float)):
    raise ValueError(
        "config.yaml has dev: " + str(DEV) + ", which is neither a count nor a "
        "proportion.\n" + _SPLIT_HELP
    )

if isinstance(DEV, float):
    if not 0 < DEV < 1:
        raise ValueError(
            "config.yaml has dev: " + str(DEV) + ". A decimal is read as a proportion, "
            "so it has to be strictly between 0 and 1 — 0.35 means about a third of each "
            "label goes to dev and the rest is held out. For a fixed count per label, "
            "write it without a decimal point.\n" + _SPLIT_HELP
        )
else:
    if DEV < 1:
        raise ValueError(
            "config.yaml has dev: " + str(DEV) + ", which leaves no dev set at all.\n"
            + _SPLIT_HELP
        )
    if DEV >= N_PER_CLASS:
        raise ValueError(
            "config.yaml has dev: " + str(DEV) + " and n_per_class: " + str(N_PER_CLASS)
            + ". A dev set of " + str(DEV) + " per class out of a sample of "
            + str(N_PER_CLASS) + " per class leaves nothing to test on.\n"
            "Either lower dev, or raise n_per_class and redraw in notebook 02.\n"
            "Then re-run the SETUP cell at the top of this notebook."
        )


# ----------------------------------------------------------------------------------
# The Drive check — every path below is only as durable as the folder ROOT points at.
# ----------------------------------------------------------------------------------
# A Colab runtime is temporary storage. Files written to it look completely normal
# until the runtime resets, at which point your pool, your gold set and your outputs
# are gone, and nobody else in the group ever saw them. So: if we are in Colab, ROOT
# has to be inside your group's Drive folder. If it is not, stop here rather than let
# a whole annotation round be written somewhere that will not survive lunch.
try:
    import google.colab          # this module only exists inside Colab
    IN_COLAB = True
except ImportError:
    IN_COLAB = False
ON_DRIVE = "/content/drive/" in str(ROOT)

if IN_COLAB and not ON_DRIVE:
    raise RuntimeError(
        "This notebook is running from a COPY that lives only in the Colab runtime.\n"
        "  found: " + str(ROOT) + "\n"
        "  wanted: a folder under /content/drive/MyDrive/\n"
        "Anything you do here — the pool you build, the gold set you annotate, the "
        "prompts you write — disappears when the runtime resets, and the rest of your "
        "group cannot see any of it.\n"
        "Re-run the SETUP cell at the top of this notebook; it will mount Drive and "
        "move you into your group's shared folder."
    )


# ----------------------------------------------------------------------------------
# Paths — worked out from the settings above. Nothing here is typed into a notebook.
# ----------------------------------------------------------------------------------
# The pool is the one file with no group and no run in its name: it is the corpus as it
# comes, the same for every group on the track, and it does not change as you iterate.
# Everything downstream is your group's own work, so it carries both.
def stem_for(track: str, group: str, run: str) -> str:
    """The front of every filename your group produces: track_group_run.

    One function, so that the name notebook 02 writes and the name notebook 06 looks
    for cannot drift apart. Anything that needs to build one of these filenames calls
    this rather than joining the three pieces itself.

    Args:
        track: which dataset track you are on.
        group: your group's name.
        run: which version of the study this is.

    Returns:
        The three joined with underscores.

    Example:
        >>> stem_for("cars50", "g1", "v1")
        'cars50_g1_v1'
    """
    return str(track) + "_" + str(group) + "_" + str(run)


STEM = stem_for(TRACK, GROUP, RUN)

POOL_PATH = ROOT / "data" / "pools" / (TRACK + "_pool.json")           # 01 writes
SAMPLE_PATH = ROOT / "data" / "gold" / (STEM + "_sample.json")         # 02 writes
GOLD_PATH = ROOT / "data" / "gold" / (STEM + "_gold.json")             # 03 writes

# Notebook 02b adds more items to a sample you have already started annotating, which
# means overwriting the file above. This is the copy of it from before that happened, so
# a top-up that goes wrong can be undone. It is written with the usual refusal to
# overwrite, which is also what stops 02b being run twice by accident.
SAMPLE_BEFORE_TOPUP_PATH = (ROOT / "data" / "gold"
                            / (STEM + "_sample_before_topup.json"))   # 02b writes

# The two halves of that gold set. Both are gold — the same adjudicated items, with a
# line drawn through them: dev is what notebook 04 iterates against; test is opened once,
# in notebook 05, and is the number your report leads with.
DEV_PATH = ROOT / "data" / "gold" / (STEM + "_dev.json")               # 03 writes
TEST_PATH = ROOT / "data" / "gold" / (STEM + "_test.json")             # 03 writes

# The rows your coders labelled differently. Notebook 03 has them already, so it writes
# them down; notebook 06 reads the file instead of signing back in to the Google Sheet
# and re-deriving the same table. It also means step 3 of notebook 06 still works after
# the sheet has been deleted or its owner has left.
DISAGREED_PATH = ROOT / "data" / "gold" / (STEM + "_disagreed.json")   # 03 writes

# Your adjudicated rows: the one `Final` label you settled on for each item, and the
# note saying why. The label ends up in the gold set either way; the note does not, and
# it is the only record of the argument you had. Written in notebook 03, step 4.
ADJUDICATED_PATH = ROOT / "data" / "gold" / (STEM + "_adjudicated.json")  # 03 writes

PRED_PATH = ROOT / "outputs" / (STEM + "_predictions.json")            # 05 writes:
#                                                          the frozen run on TEST.

# The score of every round you ran, and your one-line reason for each. Notebook 04
# writes both when it finishes iterating; 05 adds the held-out row; 06 prints them side
# by side as report section 2. They are files rather than variables because 04, 05 and
# 06 are three notebooks and nothing survives between them except what is on disk - the
# same reason your prompt versions have to be saved as files.
ROUNDS_PATH = ROOT / "outputs" / (STEM + "_rounds.json")               # 04 writes
NOTES_PATH = ROOT / "outputs" / (STEM + "_round_notes.json")           # 04 writes

# Every time the held-out set is scored, one line lands here. Nothing stops you scoring
# it twice; this is what makes the second time visible, to you and to the reader.
TESTLOG_PATH = ROOT / "outputs" / (STEM + "_test_log.jsonl")           # 05 appends

PROMPT_FILE = ROOT / "prompts" / (TRACK + ".txt")
OUT_DIR = ROOT / "outputs"

# Where notebook 02 writes down the annotation sheet it created. The sheet is the one
# handoff in this project that is not a file of its own — without this, the link to
# your group's annotation round survives only in one person's notebook output.
SHEET_PATH = ROOT / "data" / "gold" / (STEM + "_sheet.json")

# The demo pool: small, built by `prep_datasets.py <track> --demos`, lets 02-05 run
# before 01 has been done.
# Far too small for a real study — see data/pools/README.md.
DEMO_POOL_PATH = ROOT / "data" / "pools" / (TRACK + "_demo_pool.json")


def describe() -> None:
    """Print the settings, so every notebook can show what it is working on.

    Returns:
        Nothing. It prints the track, group, run, seed, split, coders, labels and
        the folder everything is written to.

    Example:
        >>> describe()
    """
    print("track", TRACK, "· group", GROUP, "· run", RUN, "· seed", SEED,
          "· n_per_class", N_PER_CLASS)
    # Two per-class counts in one config file are easy to mix up, so print the split as
    # a sentence rather than as a second bare number.
    if isinstance(DEV, float):
        print("split: dev", DEV, "of each label · test gets the rest")
    else:
        print("split: dev", DEV, "per label · test gets the rest")
    print("coders:", ", ".join(CODERS))
    print("labels order:", LABELS_ORDER)
    print("model:", MODEL or "course default", "· temperature", TEMPERATURE)
    # Where the files go. Say it every time: it is the one setting nobody edits and
    # everybody depends on, and "which folder am I actually in" is the question behind
    # most of the ways a group loses a morning's work.
    print("files:", ROOT)
    if ON_DRIVE:
        print("        ^ in Drive — your group can see these, and they survive a reset")
    else:
        print("        ^ a local checkout (not Colab)")
    return None
