"""config.py — reads config.yaml and works out every path in the project.

    from config import *

You do not edit this file. You edit **config.yaml**, right next to it. This one turns
the settings in there into the file paths that notebooks 01-05 read and write.

Every path hangs off ROOT, which is wherever this file physically sits — your group's
shared Drive folder. So there is never a path to type into a notebook, and the file
notebook 02 writes is by construction the file notebook 03 opens.
"""

from pathlib import Path

import yaml

# Anchored to THIS file rather than to the working directory, so the same path works
# whether you run a notebook from notebooks/, from the repo root, or from Colab.
ROOT = Path(__file__).resolve().parent
CONFIG_FILE = ROOT / "config.yaml"

settings = yaml.safe_load(CONFIG_FILE.read_text(encoding="utf-8"))

TRACK = settings["track"]
GROUP = settings["group"]
RUN = settings["run"]
SEED = settings["seed"]
N_PER_CLASS = settings["n_per_class"]

# Left empty in the YAML, these read as None. Downstream code expects a list of members
# and expects None to mean "no label order given", so hand it what it expects.
MEMBERS = settings["members"] or []
LABELS_ORDER = settings["labels_order"] or None


# ----------------------------------------------------------------------------------
# The Drive check — every path below is only as durable as the folder ROOT points at.
# ----------------------------------------------------------------------------------
# A Colab runtime is temporary storage. Files written to it look completely normal
# until the runtime resets, at which point your pool, your gold set and your outputs
# are gone, and nobody else in the group ever saw them. So: if we are in Colab, ROOT
# has to be inside your group's Drive folder. If it is not, stop here rather than let
# a whole annotation round be written somewhere that will not survive lunch.
try:
    import google.colab          # this module only exists inside Colab
    IN_COLAB = True
except ImportError:
    IN_COLAB = False
ON_DRIVE = "/content/drive/" in str(ROOT)

if IN_COLAB and not ON_DRIVE:
    raise RuntimeError(
        "This notebook is running from a COPY that lives only in the Colab runtime.\n"
        "  found: " + str(ROOT) + "\n"
        "  wanted: a folder under /content/drive/MyDrive/\n"
        "Anything you do here — the pool you build, the gold set you annotate, the "
        "prompts you write — disappears when the runtime resets, and the rest of your "
        "group cannot see any of it.\n"
        "Re-run the SETUP cell at the top of this notebook; it will mount Drive and "
        "move you into your group's shared folder."
    )


# ----------------------------------------------------------------------------------
# Paths — worked out from the settings above. Nothing here is typed into a notebook.
# ----------------------------------------------------------------------------------
# The pool is the one file with no group and no run in its name: it is the corpus as it
# comes, the same for every group on the track, and it does not change as you iterate.
# Everything downstream is your group's own work, so it carries both.
STEM = TRACK + "_" + GROUP + "_" + RUN

POOL_PATH = ROOT / "data" / "pools" / (TRACK + "_pool.json")           # 01 writes
SAMPLE_PATH = ROOT / "data" / "gold" / (STEM + "_sample.json")         # 02 writes
GOLD_PATH = ROOT / "data" / "gold" / (STEM + "_gold.json")             # 03 writes
PRED_PATH = ROOT / "outputs" / (STEM + "_predictions.json")            # 04 writes
ROUNDS_PATH = ROOT / "outputs" / (STEM + "_rounds.json")               # 04 writes

# Your group's reading of the model's errors - which are the scheme's fault, which are
# the model's. Written in notebook 05 and read straight back into the report, because
# it is the one part of the analysis that exists only in your heads until you type it.
TRIAGE_PATH = ROOT / "outputs" / (STEM + "_triage.json")               # 05 writes
PROMPT_FILE = ROOT / "prompts" / (TRACK + ".txt")
OUT_DIR = ROOT / "outputs"

# Where notebook 02 writes down the annotation sheet it created. The sheet is the one
# handoff in this project that is not a file of its own — without this, the link to
# your group's annotation round survives only in one person's notebook output.
SHEET_PATH = ROOT / "data" / "gold" / (STEM + "_sheet.json")

# The demo pool: small, built by `prep_datasets.py <track> --demos`, lets 02-05 run
# before 01 has been done.
# Far too small for a real study — see data/pools/README.md.
DEMO_POOL_PATH = ROOT / "data" / "pools" / (TRACK + "_demo_pool.json")


def describe():
    """Print the settings, so every notebook can show what it is working on."""
    print("track", TRACK, "· group", GROUP, "· run", RUN, "· seed", SEED,
          "· n_per_class", N_PER_CLASS)
    print("labels order:", LABELS_ORDER)
    # Where the files go. Say it every time: it is the one setting nobody edits and
    # everybody depends on, and "which folder am I actually in" is the question behind
    # most of the ways a group loses a morning's work.
    print("files:", ROOT)
    if ON_DRIVE:
        print("        ^ in Drive — your group can see these, and they survive a reset")
    else:
        print("        ^ a local checkout (not Colab)")
    return None
